package com.cmj.cmj;

import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

@Configuration
public class CorsConfig implements WebMvcConfigurer {
    @Override
    public void addCorsMappings(CorsRegistry registry) {
        registry.addMapping("/user/validate")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("GET", "POST", "PUT", "DELETE")
                .allowedHeaders("*");
        registry.addMapping("/user/create")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("POST")
                .allowedHeaders("*");
        registry.addMapping("/user/returnAllUsersByRole")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("GET")
                .allowedHeaders("*");
        registry.addMapping("/user/returnByEmail")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("GET")
                .allowedHeaders("*");
        registry.addMapping("/appointment/getAll")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("GET")
                .allowedHeaders("*");
        registry.addMapping("/user/getUserByEmail")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("GET")
                .allowedHeaders("*");
        registry.addMapping("/appointment/delete")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("DELETE")
                .allowedHeaders("*");
        registry.addMapping("/appointment/create")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("POST")
                .allowedHeaders("*");
        registry.addMapping("/appointment/searchByClientEmail")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("GET")
                .allowedHeaders("*");
        registry.addMapping("/appointment/searchById")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("GET")
                .allowedHeaders("*");
        registry.addMapping("/appointment/edit")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("PUT")
                .allowedHeaders("*");
        registry.addMapping("/user/delete")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("DELETE")
                .allowedHeaders("*");
        registry.addMapping("/user/edit")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("PUT")
                .allowedHeaders("*");
        registry.addMapping("/typepayment/returnAllTypePayments")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("GET")
                .allowedHeaders("*");
        registry.addMapping("/typepayment/create")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("POST")
                .allowedHeaders("*");
        registry.addMapping("/user/returnTypePaymentsById")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("GET")
                .allowedHeaders("*");
        registry.addMapping("/user/returnSchedulesAvailableById")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("GET")
                .allowedHeaders("*");
        registry.addMapping("/typepayment/edit")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("PUT")
                .allowedHeaders("*");
        registry.addMapping("/appointment/searchWeeklyAppointmentsByDoctor")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("GET")
                .allowedHeaders("*");
        registry.addMapping("/schedulesAvailable/create")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("POST")
                .allowedHeaders("*");
        registry.addMapping("/schedulesAvailable/edit")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("PUT")
                .allowedHeaders("*");
        registry.addMapping("/schedulesAvailable/delete")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("DELETE")
                .allowedHeaders("*");
        registry.addMapping("/typepayment/delete")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("DELETE")
                .allowedHeaders("*");
        registry.addMapping("/patientrecord/create")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("POST")
                .allowedHeaders("*");
        registry.addMapping("/patientrecord/edit")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("PUT")
                .allowedHeaders("*");
        registry.addMapping("/patientrecord/delete")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("DELETE")
                .allowedHeaders("*");
        registry.addMapping("/**")
                .allowedOrigins("http://localhost:3000")
                .allowedMethods("GET", "POST", "PUT", "DELETE")
                .allowedHeaders("*");
    }
}
